### ISSUE TITLE
Exception Value: __init__() got an unexpected keyword argument 'disabled' error in version 0.6

### ISSUE THREAD

**Issue by nicolazilio** [django-wiki/django-wiki#1058]
After upgrading to v0.6, I get the following error when trying to access the settings of a wiki page (see below).

Is there a quick fix for it?

Thanks a lot in advance.

```
Internal Server Error: /wiki/intranet-introduction/_settings/

TypeError at /wiki/intranet-introduction/_settings/
__init__() got an unexpected keyword argument 'disabled'

Request Method: GET
Request URL: .../wiki/intranet-introduction/_settings/
Django Version: 2.2.13
Python Executable: /home/nzilio/uwsgi/bin/uwsgi Python Version: 3.6.8 Python Path: ['.', '', '/home/lib/python36.zip', '/home/lib/python3.6', '/home/lib/python3.6/lib-dynload', '/home/nzilio/software/Python-3.6.8/lib/python3.6', '/home/lib/python3.6/site-packages', '/home/lib/python3.6/site-packages/odf', '/home/lib/python3.6/site-packages/odf', '/home/lib/python3.6/site-packages/odf', '/home/lib/python3.6/site-packages/odf', '/home/lib/python3.6/site-packages/odf', '/home/lib/python3.6/site-packages/odf', '/home/lib/python3.6/site-packages/odf']
Server time: Mon, 15 Jun 2020 15:18:07 +0200 Installed Applications:
['adminactions',
 'django.forms',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'djangoql',
 'simple_history',
 'import_export',
 'collection_management',
 'colorful',
 'user_management',
 'order_management',
 'guardian',
 'django.contrib.sites.apps.SitesConfig',
 'django.contrib.humanize.apps.HumanizeConfig',
 'django_nyt.apps.DjangoNytConfig',
 'mptt',
 'sekizai',
 'sorl.thumbnail',
 'wiki.apps.WikiConfig',
 'wiki.plugins.attachments.apps.AttachmentsConfig',
 'wiki.plugins.notifications.apps.NotificationsConfig',
 'wiki.plugins.images.apps.ImagesConfig',
 'wiki.plugins.macros.apps.MacrosConfig',
 'background_task',
 'formz',
 'record_approval',
 'my_admin']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'simple_history.middleware.HistoryRequestMiddleware']


Traceback:

File "/home/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/home/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/home/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "./django_project/urls.py" in decorator
  75.                 return f(request, **kwargs)

File "/home/lib/python3.6/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/home/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "/home/lib/python3.6/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  21.                 return view_func(request, *args, **kwargs)

File "/home/lib/python3.6/site-packages/django/utils/decorators.py" in _wrapper
  45.         return bound_method(*args, **kwargs)

File "/home/lib/python3.6/site-packages/wiki/decorators.py" in wrapper
  164.         return func(request, article, *args, **kwargs)

File "/home/lib/python3.6/site-packages/wiki/views/article.py" in dispatch
  733.         return super().dispatch(request, article, *args, **kwargs)

File "/home/lib/python3.6/site-packages/wiki/views/mixins.py" in dispatch
  34.         return super().dispatch(request, *args, **kwargs)

File "/home/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "/home/lib/python3.6/site-packages/wiki/views/article.py" in get
  779.             self.forms.append(Form(new_article, self.request))

File "/home/lib/python3.6/site-packages/wiki/forms.py" in __init__
  506.                 if settings.USE_BOOTSTRAP_SELECT_WIDGET

Exception Type: TypeError at /wiki/intranet-introduction/_settings/
Exception Value: __init__() got an unexpected keyword argument 'disabled'
```

**Comment by benjaoming** [comment]
Hi @nicolazilio -- there is something odd about the traceback. Can you reproduce this consistently after upgrading?

I cannot preproduce the issue on the demo website.

**Comment by nicolazilio** [comment]
Yes, I have multiple copies of my Django app and they all give this error. Interestingly, it does not affect the 'root' article, for that I can access the Settings no problem, the issue seems to affect only sub-articles.

**Comment by bverem** [comment]
I'm getting the same less-than-helpful traceback with v0.6. My superuser account is unaffected but group-permitted users are experiencing the issue.

**Comment by benjaoming** [comment]
Hi @bverem! Did you see this occur again and trace a pattern?

**Comment by ivanov17** [comment]
Same error with Django 3.1.7 and Wiki 0.7.3. I got it with a simple unprivileged test user.

```
Internal Server Error: /created-user/_settings/
Traceback (most recent call last):
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/wiki/decorators.py", line 168, in wrapper
    return func(request, article, *args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/wiki/views/article.py", line 736, in dispatch
    return super().dispatch(request, article, *args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/wiki/views/mixins.py", line 34, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/wiki/views/article.py", line 782, in get
    self.forms.append(Form(new_article, self.request))
  File "/data/projects/python/wiki/env/lib64/python3.6/site-packages/wiki/forms.py", line 512, in __init__
    if settings.USE_BOOTSTRAP_SELECT_WIDGET
TypeError: __init__() got an unexpected keyword argument 'disabled'
```
