### ISSUE TITLE
Django 1.9.1 Support for Wiki

### ISSUE THREAD

**Issue by sthikka** [django-wiki/django-wiki#520]
Hi, Thanks for the wonderful solution. Is there any plans to support Django 1.9.1 version? 

If so, can you please let me know the tentative date when we could expect it.

Thanks again!!

Best,
Sthikka

**Comment by benjaoming** [comment]
Hi there!

The current maser supports Django 1.9, and you are more than welcome to use that.

It will ship as 0.1, but help is needed:

1) Please do deploy the master and let us know if there's issues with Django 1.9
2) Please help us test the upgrade path from 0.0.24 and instructions for this

Otherwise, feel free enjoy the master, put an event in your calendar to switch to the PyPi-based releases in a month or two :)

Closing this as there's nothing specific to do about 1.9 support at the moment.

**Comment by sthikka** [comment]
Hi There,

Here is the error message that i get with Django 1.9.1 version.

InvalidTemplateLibrary at /admin/

Invalid template library specified. ImportError raised when trying to load 'mptt.templatetags.mptt_admin': cannot import name EMPTY_CHANGELIST_VALUE

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/admin/
Django Version: 	1.9.1
Exception Type: 	InvalidTemplateLibrary
Exception Value: 	

Invalid template library specified. ImportError raised when trying to load 'mptt.templatetags.mptt_admin': cannot import name EMPTY_CHANGELIST_VALUE

**Comment by benjaoming** [comment]
Not seeing this. Running django-mptt 0.8.0 with Django 1.9.

**Comment by benjaoming** [comment]
Working fine with Django 1.9.1 as well.
